query ($id: ID!){
    item(id: $id) {
        histories {
            id
            checkedAt
            depreciationAt
            disposalAt
            editUser {
                id
                name
            }
            room {
                id
                number
            }
            createdAt
        }
    }
}
