query ($sort: [[String!]!]!) {
    items(sort: $sort) {
        id
        internalId
        seal
        schoolName
        name
        code
        partId
        amount
        purchasedAt
        user {
            id
            name
        }
        course {
            id
            name
        }
        checkedAt
        room {
            id
            number
        }
        disposalAt
        depreciationAt
        editUser {
            id
            name
        }
        createdAt
        deletedAt

        parts {
            id
            partId
            name
            editUser {
                id
                name
            }
            room {
                id
                number
            }
            checkedAt
        }
    }
}
