query ($sort: [[String!]!]!) {
    items(sort: $sort) {
        id
        seal
        name
        code
        amount
        purchasedAt
        admin {
            id
            name
        }
        course {
            id
            name
        }
        checkedAt
        room {
            id
            number
        }
        disposalAt
        depreciationAt
        createdAt
        deletedAt

        children {
            id
            childId
            name
            room {
                id
                number
            }
            checkedAt

            createdAt
            deletedAt
        }
    }
}
