query ($id: ID!){
    item(id: $id) {
        id
        partId
        schoolName
        name
        code
        amount
        purchasedAt
        user {
            name
        }
        course {
            name
        }
        checkedAt
        room {
            number
        }
        disposalAt
        depreciationAt
        editUser {
            name
        }
        createdAt
        deletedAt
    }
}
