query ($text: String!){
    searchItems: items(search: $text) {
        id
        schoolName
        name
        code
        amount
        purchasedAt
        user {
            name
        }
        course {
            name
        }
        checkedAt
        room {
            number
        }
        disposalAt
        depreciationAt
        editUser {
            name
        }
        createdAt
        deletedAt
    }
}
